<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class PopulatePrintersAndAttributesTable extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $dataSet = $this->getRawDataSet();
        $this->addOrUpdateMultipleRecords($dataSet);
    }

    private function addOrUpdateMultipleRecords($dataSet)
    {
        foreach ($dataSet as $dataRow) {
            $printerArr = $this->createPrinterDataSet($dataRow);
        }
    }

    /**
     * @param $dataSet
     * @return array[]
     */
    private function createPrinterDataSet($dataSet): array
    {
        $printerDataSet = ['attributes' => [], 'fields' => []];
        $printerDataSet['fields']['model_number'] = $dataSet['model_number'];
        $printerDataSet['fields']['model_number_displayed'] = $dataSet['model_number_displayed'];

        return $printerDataSet;
    }

    private function getRawDataSet()
    {
        $dataSet = [
            [
                'manufacturer'                        => 'Sharp',
                'model_number'                        => 'MXM2651',
                'model_number_displayed'              => 'MX-M2651',
                'is_enabled'                          => 'Igen',
                'is_mfp'                              => 'Igen',
                'printing'                            => 'Fekete-fehér',
                'scanning'                            => 'Színes',
                'copying'                             => 'Fekete-fehér',
                'faxing'                              => 'Opció',
                'technology'                          => 'Lézer',
                'color_management'                    => 'Fekete-fehér',
                'papersize'                           => 'A3',
                'networked'                           => 'Hálózatos',
                'usergroupsize'                       => 'Közepes munkacsoportos',
                'name'                                => '',
                'product_url_on_manufacturer_website' => 'https://www.sharp.hu/cps/rde/xchg/hu/hs.xsl/-/html/product-details-office-print.htm?product=MXM2651',
            ],
            [
                'manufacturer'                        => 'Sharp',
                'model_number'                        => 'MXM2630',
                'model_number_displayed'              => 'MX-M2630',
                'is_enabled'                          => 'Igen',
                'is_mfp'                              => 'Igen',
                'printing'                            => 'Fekete-fehér',
                'scanning'                            => 'Színes',
                'copying'                             => 'Fekete-fehér',
                'faxing'                              => 'Opció',
                'technology'                          => 'Lézer',
                'color_management'                    => 'Fekete-fehér',
                'papersize'                           => 'A3',
                'networked'                           => 'Hálózatos',
                'usergroupsize'                       => 'Közepes munkacsoportos',
                'name'                                => '',
                'product_url_on_manufacturer_website' => 'https://www.sharp.hu/cps/rde/xchg/hu/hs.xsl/-/html/product-details-office-print.htm?product=MXM2630',
            ],
            [
                'manufacturer'                        => 'Sharp',
                'model_number'                        => 'MXM266NV',
                'model_number_displayed'              => 'MX-M266NV',
                'is_enabled'                          => 'Igen',
                'is_mfp'                              => 'Igen',
                'printing'                            => 'Fekete-fehér',
                'scanning'                            => 'Színes',
                'copying'                             => 'Fekete-fehér',
                'faxing'                              => 'Opció',
                'technology'                          => 'Lézer',
                'color_management'                    => 'Fekete-fehér',
                'papersize'                           => 'A3',
                'networked'                           => 'Hálózatos',
                'usergroupsize'                       => 'Közepes munkacsoportos',
                'name'                                => '',
                'product_url_on_manufacturer_website' => 'https://www.sharp.hu/cps/rde/xchg/hu/hs.xsl/-/html/product-details-office-print.htm?product=MXM266NV',
            ],
            [
                'manufacturer'                        => 'Sharp',
                'model_number'                        => 'AR6023NV',
                'model_number_displayed'              => 'AR-6023NV',
                'is_enabled'                          => 'Igen',
                'is_mfp'                              => 'Igen',
                'printing'                            => 'Fekete-fehér',
                'scanning'                            => 'Színes',
                'copying'                             => 'Fekete-fehér',
                'faxing'                              => '',
                'technology'                          => 'Lézer',
                'color_management'                    => 'Fekete-fehér',
                'papersize'                           => 'A3',
                'networked'                           => 'Hálózatos',
                'usergroupsize'                       => 'Kis munkacsoportos',
                'name'                                => '',
                'product_url_on_manufacturer_website' => 'https://www.sharp.hu/cps/rde/xchg/hu/hs.xsl/-/html/product-details-office-print.htm?product=AR6023NV',
            ],
            [
                'manufacturer'                        => 'Sharp',
                'model_number'                        => 'AR6020NV',
                'model_number_displayed'              => 'AR-6020NV',
                'is_enabled'                          => 'Igen',
                'is_mfp'                              => 'Igen',
                'printing'                            => 'Fekete-fehér',
                'scanning'                            => 'Színes',
                'copying'                             => 'Fekete-fehér',
                'faxing'                              => '',
                'technology'                          => 'Lézer',
                'color_management'                    => 'Fekete-fehér',
                'papersize'                           => 'A3',
                'networked'                           => 'Hálózatos',
                'usergroupsize'                       => 'Kis munkacsoportos',
                'name'                                => '',
                'product_url_on_manufacturer_website' => 'https://www.sharp.hu/cps/rde/xchg/hu/hs.xsl/-/html/product-details-office-print.htm?product=AR6020NV',
            ],
            [
                'manufacturer'                        => 'Sharp',
                'model_number'                        => 'AR6020DV',
                'model_number_displayed'              => 'AR-6020DV',
                'is_enabled'                          => 'Igen',
                'is_mfp'                              => 'Igen',
                'printing'                            => 'Fekete-fehér',
                'scanning'                            => 'Színes',
                'copying'                             => 'Fekete-fehér',
                'faxing'                              => '',
                'technology'                          => 'Lézer',
                'color_management'                    => 'Fekete-fehér',
                'papersize'                           => 'A3',
                'networked'                           => '',
                'usergroupsize'                       => 'Kis munkacsoportos',
                'name'                                => '',
                'product_url_on_manufacturer_website' => 'https://www.sharp.hu/cps/rde/xchg/hu/hs.xsl/-/html/product-details-office-print.htm?product=AR6020DV',
            ],
            [
                'manufacturer'                        => 'Sharp',
                'model_number'                        => 'AR6020V',
                'model_number_displayed'              => 'AR-6020V',
                'is_enabled'                          => 'Igen',
                'is_mfp'                              => 'Igen',
                'printing'                            => 'Fekete-fehér',
                'scanning'                            => 'Színes',
                'copying'                             => 'Fekete-fehér',
                'faxing'                              => '',
                'technology'                          => 'Lézer',
                'color_management'                    => 'Fekete-fehér',
                'papersize'                           => 'A3',
                'networked'                           => '',
                'usergroupsize'                       => 'Kis munkacsoportos',
                'name'                                => '',
                'product_url_on_manufacturer_website' => 'https://www.sharp.hu/cps/rde/xchg/hu/hs.xsl/-/html/product-details-office-print.htm?product=AR6020V',
            ],
            [
                'manufacturer'                        => 'Sharp',
                'model_number'                        => 'MXB456W',
                'model_number_displayed'              => 'MX-B456W',
                'is_enabled'                          => 'Igen',
                'is_mfp'                              => 'Igen',
                'printing'                            => 'Fekete-fehér',
                'scanning'                            => 'Színes',
                'copying'                             => 'Fekete-fehér',
                'faxing'                              => 'Alap',
                'technology'                          => 'Lézer',
                'color_management'                    => 'Fekete-fehér',
                'papersize'                           => 'A4',
                'networked'                           => 'Hálózatos',
                'usergroupsize'                       => 'Nagy munkacsoportos',
                'name'                                => '',
                'product_url_on_manufacturer_website' => 'https://www.sharp.hu/cps/rde/xchg/hu/hs.xsl/-/html/product-details-office-print.htm?product=MXB456W',
            ],
            [
                'manufacturer'                        => 'Sharp',
                'model_number'                        => 'MXB450W',
                'model_number_displayed'              => 'MX-B450W',
                'is_enabled'                          => 'Igen',
                'is_mfp'                              => 'Igen',
                'printing'                            => 'Fekete-fehér',
                'scanning'                            => 'Színes',
                'copying'                             => 'Fekete-fehér',
                'faxing'                              => 'Alap',
                'technology'                          => 'Lézer',
                'color_management'                    => 'Fekete-fehér',
                'papersize'                           => 'A4',
                'networked'                           => 'Hálózatos',
                'usergroupsize'                       => 'Nagy munkacsoportos',
                'name'                                => '',
                'product_url_on_manufacturer_website' => 'https://www.sharp.hu/cps/rde/xchg/hu/hs.xsl/-/html/product-details-office-print.htm?product=MXB450W',
            ],
            [
                'manufacturer'                        => 'Sharp',
                'model_number'                        => 'MXB356W',
                'model_number_displayed'              => 'MX-B356W',
                'is_enabled'                          => 'Igen',
                'is_mfp'                              => 'Igen',
                'printing'                            => 'Fekete-fehér',
                'scanning'                            => 'Színes',
                'copying'                             => 'Fekete-fehér',
                'faxing'                              => 'Alap',
                'technology'                          => 'Lézer',
                'color_management'                    => 'Fekete-fehér',
                'papersize'                           => 'A4',
                'networked'                           => 'Hálózatos',
                'usergroupsize'                       => 'Közepes munkacsoportos',
                'name'                                => '',
                'product_url_on_manufacturer_website' => 'https://www.sharp.hu/cps/rde/xchg/hu/hs.xsl/-/html/product-details-office-print.htm?product=MXB356W',
            ],
            [
                'manufacturer'                        => 'Sharp',
                'model_number'                        => 'MXB350W',
                'model_number_displayed'              => 'MX-B350W',
                'is_enabled'                          => 'Igen',
                'is_mfp'                              => 'Igen',
                'printing'                            => 'Fekete-fehér',
                'scanning'                            => 'Színes',
                'copying'                             => 'Fekete-fehér',
                'faxing'                              => 'Alap',
                'technology'                          => 'Lézer',
                'color_management'                    => 'Fekete-fehér',
                'papersize'                           => 'A4',
                'networked'                           => 'Hálózatos',
                'usergroupsize'                       => 'Közepes munkacsoportos',
                'name'                                => '',
                'product_url_on_manufacturer_website' => 'https://www.sharp.hu/cps/rde/xchg/hu/hs.xsl/-/html/product-details-office-print.htm?product=MXB350W',
            ],
            [
                'manufacturer'                        => 'Sharp',
                'model_number'                        => 'MXB707P',
                'model_number_displayed'              => 'MX-B707P',
                'is_enabled'                          => 'Igen',
                'is_mfp'                              => 'Nem',
                'printing'                            => 'Fekete-fehér',
                'scanning'                            => '',
                'copying'                             => '',
                'faxing'                              => '',
                'technology'                          => 'Lézer',
                'color_management'                    => 'Fekete-fehér',
                'papersize'                           => 'A4',
                'networked'                           => 'Hálózatos',
                'usergroupsize'                       => 'Nagy munkacsoportos',
                'name'                                => '',
                'product_url_on_manufacturer_website' => 'https://www.sharp.hu/cps/rde/xchg/hu/hs.xsl/-/html/product-details-office-print.htm?product=MXB707P',
            ],
            [
                'manufacturer'                        => 'Sharp',
                'model_number'                        => 'MXB557P',
                'model_number_displayed'              => 'MX-B557P',
                'is_enabled'                          => 'Igen',
                'is_mfp'                              => 'Nem',
                'printing'                            => 'Fekete-fehér',
                'scanning'                            => '',
                'copying'                             => '',
                'faxing'                              => '',
                'technology'                          => 'Lézer',
                'color_management'                    => 'Fekete-fehér',
                'papersize'                           => 'A4',
                'networked'                           => 'Hálózatos',
                'usergroupsize'                       => 'Nagy munkacsoportos',
                'name'                                => '',
                'product_url_on_manufacturer_website' => 'https://www.sharp.hu/cps/rde/xchg/hu/hs.xsl/-/html/product-details-office-print.htm?product=MXB557P',
            ],
            [
                'manufacturer'                        => 'Sharp',
                'model_number'                        => 'MXB450P',
                'model_number_displayed'              => 'MX-B450P',
                'is_enabled'                          => 'Igen',
                'is_mfp'                              => 'Nem',
                'printing'                            => 'Fekete-fehér',
                'scanning'                            => '',
                'copying'                             => '',
                'faxing'                              => '',
                'technology'                          => 'Lézer',
                'color_management'                    => 'Fekete-fehér',
                'papersize'                           => 'A4',
                'networked'                           => 'Hálózatos',
                'usergroupsize'                       => 'Nagy munkacsoportos',
                'name'                                => '',
                'product_url_on_manufacturer_website' => 'https://www.sharp.hu/cps/rde/xchg/hu/hs.xsl/-/html/product-details-office-print.htm?product=MXB450P',
            ],
            [
                'manufacturer'                        => 'Sharp',
                'model_number'                        => 'MXB350P',
                'model_number_displayed'              => 'MX-B350P',
                'is_enabled'                          => 'Igen',
                'is_mfp'                              => 'Nem',
                'printing'                            => 'Fekete-fehér',
                'scanning'                            => '',
                'copying'                             => '',
                'faxing'                              => '',
                'technology'                          => 'Lézer',
                'color_management'                    => 'Fekete-fehér',
                'papersize'                           => 'A4',
                'networked'                           => 'Hálózatos',
                'usergroupsize'                       => 'Közepes munkacsoportos',
                'name'                                => '',
                'product_url_on_manufacturer_website' => 'https://www.sharp.hu/cps/rde/xchg/hu/hs.xsl/-/html/product-details-office-print.htm?product=MXB350P',
            ],
            [
                'manufacturer'                        => 'Lexmark',
                'model_number'                        => 'MS521dn',
                'model_number_displayed'              => 'MS521dn',
                'is_enabled'                          => 'Igen',
                'is_mfp'                              => 'Nem',
                'printing'                            => 'Fekete-fehér',
                'scanning'                            => '',
                'copying'                             => '',
                'faxing'                              => '',
                'technology'                          => 'Lézer',
                'color_management'                    => 'Fekete-fehér',
                'papersize'                           => 'A4',
                'networked'                           => 'Hálózatos',
                'usergroupsize'                       => 'Közepes munkacsoportos',
                'name'                                => '',
                'product_url_on_manufacturer_website' => 'https://www.lexmark.com/hu_hu/printer/11835/Lexmark-MS521dn',
            ],
            [
                'manufacturer'                        => 'Lexmark',
                'model_number'                        => 'MS621dn',
                'model_number_displayed'              => 'MS621dn',
                'is_enabled'                          => 'Igen',
                'is_mfp'                              => 'Nem',
                'printing'                            => 'Fekete-fehér',
                'scanning'                            => '',
                'copying'                             => '',
                'faxing'                              => '',
                'technology'                          => 'Lézer',
                'color_management'                    => 'Fekete-fehér',
                'papersize'                           => 'A4',
                'networked'                           => 'Hálózatos',
                'usergroupsize'                       => 'Nagy munkacsoportos',
                'name'                                => '',
                'product_url_on_manufacturer_website' => 'https://www.lexmark.com/hu_hu/printer/11837/Lexmark-MS621dn',
            ],
            [
                'manufacturer'                        => 'Lexmark',
                'model_number'                        => 'MS711dn',
                'model_number_displayed'              => 'MS711dn',
                'is_enabled'                          => 'Igen',
                'is_mfp'                              => 'Nem',
                'printing'                            => 'Fekete-fehér',
                'scanning'                            => '',
                'copying'                             => '',
                'faxing'                              => '',
                'technology'                          => 'Lézer',
                'color_management'                    => 'Fekete-fehér',
                'papersize'                           => 'A4',
                'networked'                           => 'Hálózatos',
                'usergroupsize'                       => 'Nagy munkacsoportos',
                'name'                                => '',
                'product_url_on_manufacturer_website' => 'https://www.lexmark.com/hu_hu/printer/8268/Lexmark-MS711dn',
            ],
            [
                'manufacturer'                        => 'Lexmark',
                'model_number'                        => 'MS823dn',
                'model_number_displayed'              => 'MS823dn',
                'is_enabled'                          => 'Igen',
                'is_mfp'                              => 'Nem',
                'printing'                            => 'Fekete-fehér',
                'scanning'                            => '',
                'copying'                             => '',
                'faxing'                              => '',
                'technology'                          => 'Lézer',
                'color_management'                    => 'Fekete-fehér',
                'papersize'                           => 'A4',
                'networked'                           => 'Hálózatos',
                'usergroupsize'                       => 'Nagy munkacsoportos',
                'name'                                => '',
                'product_url_on_manufacturer_website' => 'https://www.lexmark.com/hu_hu/printer/12443/Lexmark-MS823dn',
            ],
            [
                'manufacturer'                        => 'Lexmark',
                'model_number'                        => 'CS622de',
                'model_number_displayed'              => 'CS622de',
                'is_enabled'                          => 'Igen',
                'is_mfp'                              => 'Nem',
                'printing'                            => 'Színes',
                'scanning'                            => '',
                'copying'                             => '',
                'faxing'                              => '',
                'technology'                          => 'Lézer',
                'color_management'                    => 'Színes',
                'papersize'                           => 'A4',
                'networked'                           => 'Hálózatos',
                'usergroupsize'                       => 'Nagy munkacsoportos',
                'name'                                => '',
                'product_url_on_manufacturer_website' => 'https://www.lexmark.com/hu_hu/printer/12467/Lexmark-CS622de',
            ],
            [
                'manufacturer'                        => 'Lexmark',
                'model_number'                        => 'MX521de',
                'model_number_displayed'              => 'MX521de',
                'is_enabled'                          => 'Igen',
                'is_mfp'                              => 'Igen',
                'printing'                            => 'Fekete-fehér',
                'scanning'                            => 'Színes',
                'copying'                             => 'Fekete-fehér',
                'faxing'                              => '',
                'technology'                          => 'Lézer',
                'color_management'                    => 'Fekete-fehér',
                'papersize'                           => 'A4',
                'networked'                           => 'Hálózatos',
                'usergroupsize'                       => 'Közepes munkacsoportos',
                'name'                                => '',
                'product_url_on_manufacturer_website' => 'https://www.lexmark.com/hu_hu/printer/11845/Lexmark-MX521de',
            ],
            [
                'manufacturer'                        => 'Lexmark',
                'model_number'                        => 'MX521ade',
                'model_number_displayed'              => 'MX521ade',
                'is_enabled'                          => 'Igen',
                'is_mfp'                              => 'Igen',
                'printing'                            => 'Fekete-fehér',
                'scanning'                            => 'Színes',
                'copying'                             => 'Fekete-fehér',
                'faxing'                              => 'Alap',
                'technology'                          => 'Lézer',
                'color_management'                    => 'Fekete-fehér',
                'papersize'                           => 'A4',
                'networked'                           => 'Hálózatos',
                'usergroupsize'                       => 'Közepes munkacsoportos',
                'name'                                => '',
                'product_url_on_manufacturer_website' => 'https://www.lexmark.com/hu_hu/printer/11846/Lexmark-MX521ade',
            ],
            [
                'manufacturer'                        => 'Lexmark',
                'model_number'                        => 'MX522adhe',
                'model_number_displayed'              => 'MX522adhe',
                'is_enabled'                          => 'Igen',
                'is_mfp'                              => 'Igen',
                'printing'                            => 'Fekete-fehér',
                'scanning'                            => 'Színes',
                'copying'                             => 'Fekete-fehér',
                'faxing'                              => 'Alap',
                'technology'                          => 'Lézer',
                'color_management'                    => 'Fekete-fehér',
                'papersize'                           => 'A4',
                'networked'                           => 'Hálózatos',
                'usergroupsize'                       => 'Közepes munkacsoportos',
                'name'                                => '',
                'product_url_on_manufacturer_website' => 'https://www.lexmark.com/hu_hu/printer/11848/Lexmark-MX522adhe',
            ],
            [
                'manufacturer'                        => 'Lexmark',
                'model_number'                        => 'MX622adhe',
                'model_number_displayed'              => 'MX622adhe',
                'is_enabled'                          => 'Igen',
                'is_mfp'                              => 'Igen',
                'printing'                            => 'Fekete-fehér',
                'scanning'                            => 'Színes',
                'copying'                             => 'Fekete-fehér',
                'faxing'                              => 'Alap',
                'technology'                          => 'Lézer',
                'color_management'                    => 'Fekete-fehér',
                'papersize'                           => 'A4',
                'networked'                           => 'Hálózatos',
                'usergroupsize'                       => 'Nagy munkacsoportos',
                'name'                                => '',
                'product_url_on_manufacturer_website' => 'https://www.lexmark.com/hu_hu/printer/11850/Lexmark-MX622adhe',
            ],
            [
                'manufacturer'                        => 'Lexmark',
                'model_number'                        => 'MX722ade',
                'model_number_displayed'              => 'MX722ade',
                'is_enabled'                          => 'Igen',
                'is_mfp'                              => 'Igen',
                'printing'                            => 'Fekete-fehér',
                'scanning'                            => 'Színes',
                'copying'                             => 'Fekete-fehér',
                'faxing'                              => 'Alap',
                'technology'                          => 'Lézer',
                'color_management'                    => 'Fekete-fehér',
                'papersize'                           => 'A4',
                'networked'                           => 'Hálózatos',
                'usergroupsize'                       => 'Nagy munkacsoportos',
                'name'                                => '',
                'product_url_on_manufacturer_website' => 'https://www.lexmark.com/hu_hu/printer/12446/Lexmark-MX722ade',
            ],
            [
                'manufacturer'                        => 'Lexmark',
                'model_number'                        => 'CX522ade',
                'model_number_displayed'              => 'CX522ade',
                'is_enabled'                          => 'Igen',
                'is_mfp'                              => 'Igen',
                'printing'                            => 'Színes',
                'scanning'                            => 'Színes',
                'copying'                             => 'Színes',
                'faxing'                              => 'Alap',
                'technology'                          => 'Lézer',
                'color_management'                    => 'Színes',
                'papersize'                           => 'A4',
                'networked'                           => 'Hálózatos',
                'usergroupsize'                       => 'Közepes munkacsoportos',
                'name'                                => '',
                'product_url_on_manufacturer_website' => 'https://www.lexmark.com/hu_hu/printer/12469/Lexmark-CX522ade',
            ],
            [
                'manufacturer'                        => 'Lexmark',
                'model_number'                        => 'CX622ade',
                'model_number_displayed'              => 'CX622ade',
                'is_enabled'                          => 'Igen',
                'is_mfp'                              => 'Igen',
                'printing'                            => 'Színes',
                'scanning'                            => 'Színes',
                'copying'                             => 'Színes',
                'faxing'                              => 'Alap',
                'technology'                          => 'Lézer',
                'color_management'                    => 'Színes',
                'papersize'                           => 'A4',
                'networked'                           => 'Hálózatos',
                'usergroupsize'                       => 'Nagy munkacsoportos',
                'name'                                => '',
                'product_url_on_manufacturer_website' => 'https://www.lexmark.com/hu_hu/printer/12470/Lexmark-CX622ade',
            ],
            [
                'manufacturer'                        => 'Lexmark',
                'model_number'                        => 'CX725de',
                'model_number_displayed'              => 'CX725de',
                'is_enabled'                          => 'Igen',
                'is_mfp'                              => 'Igen',
                'printing'                            => 'Színes',
                'scanning'                            => 'Színes',
                'copying'                             => 'Színes',
                'faxing'                              => 'Alap',
                'technology'                          => 'Lézer',
                'color_management'                    => 'Színes',
                'papersize'                           => 'A4',
                'networked'                           => 'Hálózatos',
                'usergroupsize'                       => 'Nagy munkacsoportos',
                'name'                                => '',
                'product_url_on_manufacturer_website' => 'https://www.lexmark.com/hu_hu/printer/10164/Lexmark-CX725de',
            ],
            [
                'manufacturer'                        => 'Lexmark',
                'model_number'                        => 'CX725dhe',
                'model_number_displayed'              => 'CX725dhe',
                'is_enabled'                          => 'Igen',
                'is_mfp'                              => 'Igen',
                'printing'                            => 'Színes',
                'scanning'                            => 'Színes',
                'copying'                             => 'Színes',
                'faxing'                              => 'Alap',
                'technology'                          => 'Lézer',
                'color_management'                    => 'Színes',
                'papersize'                           => 'A4',
                'networked'                           => 'Hálózatos',
                'usergroupsize'                       => 'Nagy munkacsoportos',
                'name'                                => '',
                'product_url_on_manufacturer_website' => 'https://www.lexmark.com/hu_hu/printer/10263/Lexmark-CX725dhe',
            ],

        ];
        return $dataSet;
    }
}
